"""
Local backtest entrypoint for the SoAI 2026 AI Algorithmic Trading Competition.

What this file does
-------------------
* Loads daily-bar CSVs for the symbol universe declared in
  ``strategies/params.py``.
* Runs the strategy defined in ``strategies/strategy.py`` against that
  data using Lumibot's :class:`PandasDataBacktesting` engine.
* Applies optional, fully configurable execution-cost models (fees and
  slippage) so your local results better approximate live execution.

Quick start
-----------
1. Install dependencies (see ``README.md``).
2. Generate or download a CSV named ``{SYMBOL}_daily.csv`` for every
   symbol you want to trade into the ``data/`` folder. Required columns:
   ``open, high, low, close, volume, timestamp`` (timestamp ISO-8601 UTC).
   ``scripts/fetch_stock_data.py`` pulls real data via yfinance.
3. List those symbols in ``strategies/params.py``.
4. Run::

       python backtest.py

The local backtest is for development only. The official competition
score is generated by the IntelligenceX technical team in a standardized
environment over the trading window 16 August to 15 September 2026 (SGT).

Useful Lumibot documentation
----------------------------
* Backtesting overview:  https://lumibot.lumiwealth.com/backtesting.html
* Pandas (CSV) mode:     https://lumibot.lumiwealth.com/backtesting.pandas.html
* Trading fees entity:   https://lumibot.lumiwealth.com/entities.trading_fee.html
* Trading slippage:      https://lumibot.lumiwealth.com/entities.trading_slippage.html
"""

from pathlib import Path
from datetime import datetime, timezone

import pandas as pd
from lumibot.backtesting import PandasDataBacktesting
from lumibot.entities import Asset, Data, TradingFee, TradingSlippage

from strategies import params as P
from strategies.strategy import Strategy


# ---------------------------------------------------------------------------
# Configurable settings - edit these to match your local environment.
# ---------------------------------------------------------------------------

DATA_DIR = Path(__file__).resolve().parent / "data"

BUDGET = 1_000_000

# The account quote asset for equities: USD as a forex pair, which is what
# a bare stock symbol resolves against by default.
QUOTE_ASSET = Asset(symbol="USD", asset_type=Asset.AssetType.FOREX)

# Backtest window, both bounds inclusive. Leave either as None to use the
# full range available in the CSV files.
BACKTEST_START: datetime | None = None
BACKTEST_END: datetime | None = None

STRICT_MISSING_SYMBOLS = False
QUIET_LOGS = False


# ---------------------------------------------------------------------------
# Execution-cost model - fees and slippage charged on every fill.
# ---------------------------------------------------------------------------
# The competition charges a uniform 2 basis points on all trades across both
# asset classes.

USE_CUSTOM_EXECUTION_COSTS = True

BUY_FLAT_FEE = 0.0
SELL_FLAT_FEE = 0.0

BUY_PERCENT_FEE = 0.0002
SELL_PERCENT_FEE = 0.0002

PER_CONTRACT_FEE = 0.0

BUY_SLIPPAGE_AMOUNT = 0.0
SELL_SLIPPAGE_AMOUNT = 0.0


# ---------------------------------------------------------------------------
# Internal helpers - you generally do not need to edit anything below.
# ---------------------------------------------------------------------------

def _execution_cost_kwargs() -> dict:
    if not USE_CUSTOM_EXECUTION_COSTS:
        return {}

    buy_fee = TradingFee(
        flat_fee=float(BUY_FLAT_FEE),
        percent_fee=float(BUY_PERCENT_FEE),
        per_contract_fee=float(PER_CONTRACT_FEE),
        maker=True,
        taker=True,
    )
    sell_fee = TradingFee(
        flat_fee=float(SELL_FLAT_FEE),
        percent_fee=float(SELL_PERCENT_FEE),
        per_contract_fee=float(PER_CONTRACT_FEE),
        maker=True,
        taker=True,
    )
    buy_slippage = TradingSlippage(amount=float(BUY_SLIPPAGE_AMOUNT))
    sell_slippage = TradingSlippage(amount=float(SELL_SLIPPAGE_AMOUNT))

    return {
        "buy_trading_fees": [buy_fee],
        "sell_trading_fees": [sell_fee],
        "buy_trading_slippages": [buy_slippage],
        "sell_trading_slippages": [sell_slippage],
    }


def _normalize_symbol(symbol: str) -> str:
    return symbol.replace("/", "_").replace("\\", "_").replace(".", "_")


def _read_raw_csv(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, usecols=["open", "high", "low", "close", "volume", "timestamp"])
    df["datetime"] = pd.to_datetime(df["timestamp"], utc=True, errors="coerce")
    df = df.dropna(subset=["datetime"]).drop(columns=["timestamp"])
    df = df.set_index("datetime").sort_index()
    return df[["open", "high", "low", "close", "volume"]]


def _as_utc(dt: datetime) -> datetime:
    if dt.tzinfo is None:
        return dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


def _load_pandas_data():
    symbols = list(dict.fromkeys(P.STOCK_SLEEVE_SYMBOLS + [P.STOCK_BENCH]))
    pandas_data: dict[Asset, Data] = {}
    starts: list[pd.Timestamp] = []
    ends: list[pd.Timestamp] = []
    missing_symbols: list[str] = []

    for symbol in symbols:
        filename = f"{_normalize_symbol(symbol)}_daily.csv"
        path = DATA_DIR / filename
        if not path.exists():
            print(f"[WARN] Missing CSV for {symbol}: {path}")
            missing_symbols.append(symbol)
            continue

        df = _read_raw_csv(path)
        if df.empty:
            print(f"[WARN] Empty CSV for {symbol}: {path}")
            continue

        asset = Asset(symbol=symbol, asset_type=Asset.AssetType.STOCK)
        pandas_data[asset] = Data(asset, df, timestep="day", quote=QUOTE_ASSET)
        starts.append(df.index.min())
        ends.append(df.index.max())

    return pandas_data, starts, ends, missing_symbols


def _bench_total_return(pandas_data: dict, start, end) -> float | None:
    """Buy-and-hold total return of the BENCH5 composite over [start, end],
    computed straight from the local CSV we already loaded - no network
    calls. Returns None if BENCH5 wasn't loaded."""
    bench_asset = Asset(symbol=P.STOCK_BENCH, asset_type=Asset.AssetType.STOCK)
    data_obj = pandas_data.get(bench_asset)
    if data_obj is None:
        return None
    df = data_obj.df
    window = df.loc[(df.index >= start) & (df.index <= end)]
    if window.empty:
        window = df
    first_close = float(window["close"].iloc[0])
    last_close = float(window["close"].iloc[-1])
    if first_close <= 0:
        return None
    return (last_close / first_close) - 1.0


def _print_terminal_summary(analysis, strat, pandas_data, backtesting_start, backtesting_end) -> None:
    """Print a clean, always-visible results summary to the terminal.

    Historically the only way to see results was to open the generated
    tearsheet HTML - backtest.py only ever logged per-iteration trade
    fills to the terminal. This prints the headline numbers directly,
    computed from data we already have locally (no Yahoo/network calls,
    which is what was silently breaking the tearsheet's own benchmark
    comparison for the synthetic BENCH5 symbol - see benchmark_asset=None
    below).
    """
    print("\n" + "=" * 60)
    print("RESULTS SUMMARY")
    print("=" * 60)

    span_days = (backtesting_end - backtesting_start).days
    years = span_days / 365.25 if span_days > 0 else 0.0

    initial_budget = getattr(strat, "initial_budget", BUDGET)
    final_value = None
    try:
        final_value = strat.get_portfolio_value()
    except Exception:
        pass

    if final_value is not None and initial_budget:
        total_return = (final_value / initial_budget) - 1.0
        print(f"Initial budget:     ${initial_budget:,.2f}")
        print(f"Final portfolio:    ${final_value:,.2f}")
        print(f"Total return:       {total_return:+.2%}")
        if years > 0:
            cagr = (final_value / initial_budget) ** (1 / years) - 1
            print(f"CAGR:               {cagr:+.2%}  (over {years:.2f} years)")
    else:
        print("[WARN] Could not read final portfolio value from the strategy object.")

    bench_return = _bench_total_return(pandas_data, backtesting_start, backtesting_end)
    if bench_return is not None:
        print(f"BENCH5 buy&hold:    {bench_return:+.2%}  (5-stock equal-weight composite)")
    else:
        print("[WARN] BENCH5 not found in pandas_data - run scripts/build_benchmark.py first.")

    # Pull the daily Portfolio Value / Drawdown % lines we log via
    # add_line() in strategy.py for a max-drawdown and rough Sharpe figure,
    # entirely from local data collected during the run.
    try:
        lines_df = strat.get_lines_df()
        if lines_df is not None and not lines_df.empty:
            dd_col = next((c for c in lines_df.columns if "Drawdown" in str(c)), None)
            if dd_col is not None:
                max_dd = lines_df[dd_col].min()
                print(f"Max drawdown:       {max_dd:.2f}%  (from logged Drawdown % line)")
            pv_col = next((c for c in lines_df.columns if "Portfolio Value" in str(c)), None)
            if pv_col is not None:
                daily_returns = lines_df[pv_col].pct_change().dropna()
                if len(daily_returns) > 1 and daily_returns.std() > 0:
                    sharpe = (daily_returns.mean() / daily_returns.std()) * (252 ** 0.5)
                    print(f"Sharpe (approx):    {sharpe:.2f}  (annualized from daily Portfolio Value line)")
    except Exception as exc:
        print(f"[INFO] Skipped lines-based stats (get_lines_df unavailable or unexpected shape): {exc}")

    print("=" * 60)
    print("Full tearsheet, trades, and indicator charts are in logs/ - ")
    print("this terminal summary is a quick check, not a replacement for them.")
    print("=" * 60 + "\n")


def run_backtest() -> None:
    if not DATA_DIR.exists():
        raise RuntimeError(f"Data directory not found: {DATA_DIR}")

    pandas_data, starts, ends, missing_symbols = _load_pandas_data()
    if not pandas_data:
        raise RuntimeError(f"No valid CSV data loaded from {DATA_DIR}")
    if STRICT_MISSING_SYMBOLS and missing_symbols:
        missing = ", ".join(sorted(missing_symbols))
        raise RuntimeError(f"Missing CSV files for required symbols: {missing}")

    backtesting_start = max(starts).to_pydatetime()
    backtesting_end = min(ends).to_pydatetime()
    if BACKTEST_START is not None:
        backtesting_start = max(backtesting_start, _as_utc(BACKTEST_START))
    if BACKTEST_END is not None:
        backtesting_end = min(backtesting_end, _as_utc(BACKTEST_END))
    if backtesting_start >= backtesting_end:
        raise RuntimeError(
            "No overlapping datetime range across loaded symbols. "
            "Please align downloaded date ranges first."
        )

    span_days = (backtesting_end - backtesting_start).days
    print(
        f"[INFO] Loaded {len(pandas_data)} assets from {DATA_DIR}\n"
        f"[INFO] Quote asset: {QUOTE_ASSET}\n"
        f"[INFO] Backtest window: {backtesting_start} -> {backtesting_end} "
        f"({span_days} days)"
    )

    # benchmark_asset is intentionally None, not P.STOCK_BENCH. Lumibot's
    # built-in tearsheet benchmark comparison fetches the benchmark's
    # returns via Yahoo Finance internally regardless of what's in
    # pandas_data - fine for a real ticker like AAPL, but BENCH5 is a
    # synthetic symbol that doesn't exist on Yahoo, so that fetch 404s
    # ("possibly delisted; no timezone found") and silently degrades the
    # tearsheet's benchmark rows/plot. We compute the BENCH5 comparison
    # ourselves in _print_terminal_summary() from the local CSV instead,
    # which is both correct and has no network dependency.
    analysis, strat = Strategy.run_backtest(
        PandasDataBacktesting,
        backtesting_start,
        backtesting_end,
        pandas_data=pandas_data,
        budget=BUDGET,
        quote_asset=QUOTE_ASSET,
        benchmark_asset=None,
        quiet_logs=QUIET_LOGS,
        **_execution_cost_kwargs(),
    )

    _print_terminal_summary(analysis, strat, pandas_data, backtesting_start, backtesting_end)


if __name__ == "__main__":
    run_backtest()
