"""
Local backtest entrypoint for the SoAI 2026 AI Algorithmic Trading Competition.

What this file does
-------------------
* Loads minute-bar CSVs for the symbol universe declared in
  ``strategies/params.py``.
* Runs the strategy defined in ``strategies/strategy.py`` against that
  data using Lumibot's :class:`PandasDataBacktesting` engine.
* Applies optional, fully configurable execution-cost models (fees and
  slippage) so your local results better approximate live execution.

Quick start
-----------
1. Activate your virtual environment and install dependencies
   (see ``README.md``).
2. Generate or download a CSV named ``{SYMBOL}_1m_spot.csv`` for every
   symbol you want to trade into the ``data/`` folder. Required columns:
   ``open, high, low, close, volume, timestamp`` (timestamp ISO-8601 UTC).
   ``scripts/generate_synthetic_data.py`` writes synthetic files for local
   development.
3. List those symbols in ``strategies/params.py``.
4. Run::

       python backtest.py

The local backtest is for development only. The official competition
score is generated by the IntelligenceX technical team in a standardized
environment over the trading window 16 August to 15 September 2026 (SGT).

Useful Lumibot documentation
----------------------------
* Backtesting overview:  https://lumibot.lumiwealth.com/backtesting.html
* Pandas (CSV) mode:     https://lumibot.lumiwealth.com/backtesting.pandas.html
* Trading fees entity:   https://lumibot.lumiwealth.com/entities.trading_fee.html
* Trading slippage:      https://lumibot.lumiwealth.com/entities.trading_slippage.html
"""

from pathlib import Path
from datetime import datetime, timezone

import pandas as pd
from lumibot.backtesting import PandasDataBacktesting
from lumibot.entities import Asset, Data, TradingFee, TradingSlippage

from strategies import params as P
from strategies.strategy import Strategy


# ---------------------------------------------------------------------------
# Configurable settings - edit these to match your local environment.
# ---------------------------------------------------------------------------

# Directory containing the CSV bar files. Each symbol must have a file named
# ``{SYMBOL}_1m_spot.csv`` here. Required columns: open, high, low, close,
# volume, timestamp (UTC, ISO-8601).
DATA_DIR = Path(__file__).resolve().parent / "data"

# Starting cash for the backtest, in the quote currency below.
BUDGET = 1_000_000

# The account quote asset. Lumibot holds cash as a position in this asset
# and uses it to resolve crypto pairs, so it has to be the same asset the
# price data is registered under in _load_pandas_data(). A mismatch is
# quiet rather than loud: history lookups return nothing, get_cash()
# returns None, and the strategy sits flat for the whole run.
QUOTE_ASSET = Asset(symbol="USD", asset_type=Asset.AssetType.CRYPTO)

# Backtest window, both bounds inclusive. Leave either as None to use the
# full range available in the CSV files.
#
# A window that falls outside the data range shrinks the run instead of
# failing, because the harness intersects the two. A window of 1 to 29
# August against CSVs that end on 4 August leaves four days, well short of
# the 20 days of history the slow SMA needs before it can produce a signal.
# The "Backtest window" line printed at the start of a run shows the range
# actually used.
BACKTEST_START: datetime | None = None
BACKTEST_END: datetime | None = None

# When True, the harness aborts if a symbol declared in ``params.py`` has
# no matching CSV in ``DATA_DIR``. When False the symbol is skipped with a
# warning, which is useful while iterating on a subset of the universe.
STRICT_MISSING_SYMBOLS = False

# Lumibot logs at INFO on every iteration. Set True for a quieter run.
QUIET_LOGS = False


# ---------------------------------------------------------------------------
# Execution-cost model - fees and slippage charged on every fill.
# ---------------------------------------------------------------------------
# Set USE_CUSTOM_EXECUTION_COSTS = False to fall back to Lumibot defaults.
# See the Trading Fee / Slippage docs linked in the module docstring for the
# exact semantics of each field.
#
# The competition charges a uniform 2 basis points on all trades across both
# asset classes, so BUY_PERCENT_FEE and SELL_PERCENT_FEE are set to 0.0002
# to approximate official execution locally.

USE_CUSTOM_EXECUTION_COSTS = True

# Per-trade flat fee charged on every fill (quote currency).
BUY_FLAT_FEE = 0.0
SELL_FLAT_FEE = 0.0

# Fee as a fraction of trade notional. 0.0002 == 2 basis points.
BUY_PERCENT_FEE = 0.0002
SELL_PERCENT_FEE = 0.0002

# Per-contract fee (only relevant for options / futures).
PER_CONTRACT_FEE = 0.0

# Per-share slippage in price units, applied in the adverse direction
# (buys fill higher, sells fill lower).
BUY_SLIPPAGE_AMOUNT = 0.0
SELL_SLIPPAGE_AMOUNT = 0.0


# ---------------------------------------------------------------------------
# Internal helpers - you generally do not need to edit anything below.
# ---------------------------------------------------------------------------

def _execution_cost_kwargs() -> dict:
    """Build Lumibot-compatible fee/slippage kwargs for ``run_backtest``."""
    if not USE_CUSTOM_EXECUTION_COSTS:
        return {}

    buy_fee = TradingFee(
        flat_fee=float(BUY_FLAT_FEE),
        percent_fee=float(BUY_PERCENT_FEE),
        per_contract_fee=float(PER_CONTRACT_FEE),
        maker=True,
        taker=True,
    )
    sell_fee = TradingFee(
        flat_fee=float(SELL_FLAT_FEE),
        percent_fee=float(SELL_PERCENT_FEE),
        per_contract_fee=float(PER_CONTRACT_FEE),
        maker=True,
        taker=True,
    )
    buy_slippage = TradingSlippage(amount=float(BUY_SLIPPAGE_AMOUNT))
    sell_slippage = TradingSlippage(amount=float(SELL_SLIPPAGE_AMOUNT))

    return {
        "buy_trading_fees": [buy_fee],
        "sell_trading_fees": [sell_fee],
        "buy_trading_slippages": [buy_slippage],
        "sell_trading_slippages": [sell_slippage],
    }


def _normalize_symbol(symbol: str) -> str:
    """Translate a symbol into a filesystem-safe filename stem."""
    return symbol.replace("/", "_").replace("\\", "_").replace(".", "_")


def _read_raw_csv(path: Path) -> pd.DataFrame:
    """
    Read a minute-bar CSV into the shape Lumibot's Pandas backtester expects.

    Returns a DataFrame indexed by timezone-aware (UTC) datetimes with the
    five OHLCV columns in canonical order.
    """
    df = pd.read_csv(path, usecols=["open", "high", "low", "close", "volume", "timestamp"])
    df["datetime"] = pd.to_datetime(df["timestamp"], utc=True, errors="coerce")
    df = df.dropna(subset=["datetime"]).drop(columns=["timestamp"])
    df = df.set_index("datetime").sort_index()
    return df[["open", "high", "low", "close", "volume"]]


def _as_utc(dt: datetime) -> datetime:
    """Return a timezone-aware UTC datetime for safe comparisons."""
    if dt.tzinfo is None:
        return dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


def _load_pandas_data() -> tuple[dict[Asset, Data], list[pd.Timestamp], list[pd.Timestamp], list[str]]:
    """
    Build the ``{Asset: Data}`` mapping consumed by ``PandasDataBacktesting``.

    Symbols are de-duplicated, classified as stock vs crypto via
    ``params.CRYPTO_SYMBOLS``, and skipped (with a warning) when their CSV
    is missing or empty.

    Crypto assets are registered against ``QUOTE_ASSET``. The strategy has
    to request history with the same asset and quote or the lookup misses.
    """
    symbols = list(
        dict.fromkeys(P.STOCK_SLEEVE_SYMBOLS + P.CRYPTO_SLEEVE_SYMBOLS + [P.STOCK_BENCH, P.CRYPTO_BENCH])
    )
    pandas_data: dict[Asset, Data] = {}
    starts: list[pd.Timestamp] = []
    ends: list[pd.Timestamp] = []
    missing_symbols: list[str] = []
    stock_quote = Asset(symbol="USD", asset_type=Asset.AssetType.FOREX)

    for symbol in symbols:
        filename = f"{_normalize_symbol(symbol)}_1m_spot.csv"
        path = DATA_DIR / filename
        if not path.exists():
            print(f"[WARN] Missing CSV for {symbol}: {path}")
            missing_symbols.append(symbol)
            continue

        df = _read_raw_csv(path)
        if df.empty:
            print(f"[WARN] Empty CSV for {symbol}: {path}")
            continue

        is_crypto = symbol in P.CRYPTO_SYMBOLS
        asset = Asset(
            symbol=symbol,
            asset_type=Asset.AssetType.CRYPTO if is_crypto else Asset.AssetType.STOCK,
        )
        quote = QUOTE_ASSET if is_crypto else stock_quote
        pandas_data[asset] = Data(asset, df, timestep="minute", quote=quote)
        starts.append(df.index.min())
        ends.append(df.index.max())

    return pandas_data, starts, ends, missing_symbols


def run_backtest() -> None:
    """
    Run the Pandas / CSV backtest against ``strategies.strategy.Strategy``.

    Docs: https://lumibot.lumiwealth.com/backtesting.pandas.html
    """
    if not DATA_DIR.exists():
        raise RuntimeError(f"Data directory not found: {DATA_DIR}")

    pandas_data, starts, ends, missing_symbols = _load_pandas_data()
    if not pandas_data:
        raise RuntimeError(f"No valid CSV data loaded from {DATA_DIR}")
    if STRICT_MISSING_SYMBOLS and missing_symbols:
        missing = ", ".join(sorted(missing_symbols))
        raise RuntimeError(f"Missing CSV files for required symbols: {missing}")

    # Clamp the backtest window to the intersection of every symbol's data
    # range so Lumibot never tries to step past the end of any series.
    backtesting_start = max(starts).to_pydatetime()
    backtesting_end = min(ends).to_pydatetime()
    if BACKTEST_START is not None:
        backtesting_start = max(backtesting_start, _as_utc(BACKTEST_START))
    if BACKTEST_END is not None:
        backtesting_end = min(backtesting_end, _as_utc(BACKTEST_END))
    if backtesting_start >= backtesting_end:
        raise RuntimeError(
            "No overlapping datetime range across loaded symbols. "
            "Please align downloaded date ranges first."
        )

    span_days = (backtesting_end - backtesting_start).days
    print(
        f"[INFO] Loaded {len(pandas_data)} assets from {DATA_DIR}\n"
        f"[INFO] Quote asset: {QUOTE_ASSET}\n"
        f"[INFO] Backtest window: {backtesting_start} -> {backtesting_end} "
        f"({span_days} days)"
    )
    if span_days < Strategy.SLOW_SMA_DAYS + 1:
        print(
            f"[WARN] The window is shorter than the {Strategy.SLOW_SMA_DAYS}-day "
            f"slow SMA needs, so no entry signal can form and the run will "
            f"produce no trades. Widen the data or clear BACKTEST_START/END."
        )

    Strategy.run_backtest(
        PandasDataBacktesting,
        backtesting_start,
        backtesting_end,
        pandas_data=pandas_data,
        budget=BUDGET,
        quote_asset=QUOTE_ASSET,
        benchmark_asset=P.STOCK_BENCH,
        quiet_logs=QUIET_LOGS,
        **_execution_cost_kwargs(),
    )


if __name__ == "__main__":
    run_backtest()
